import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
import datetime
import logging
import config

logger = logging.getLogger(__name__)

def generate_html_report(items):
    """
    Generate an HTML email body from the analyzed items.
    """
    date_str = datetime.datetime.now().strftime("%Y-%m-%d")
    
    html_content = f"""
    <html>
    <head>
        <style>
            body {{ font-family: Arial, sans-serif; line-height: 1.6; color: #333; }}
            .container {{ max-width: 800px; margin: 0 auto; padding: 20px; }}
            .header {{ background-color: #2c3e50; color: #fff; padding: 20px; text-align: center; border-radius: 5px 5px 0 0; }}
            .item {{ border: 1px solid #ddd; margin-bottom: 20px; padding: 20px; border-radius: 5px; background-color: #f9f9f9; }}
            .item h2 {{ margin-top: 0; color: #2980b9; }}
            .meta {{ font-size: 0.9em; color: #7f8c8d; margin-bottom: 10px; }}
            .category {{ display: inline-block; background-color: #e74c3c; color: #fff; padding: 2px 8px; border-radius: 3px; font-size: 0.8em; }}
            .insight {{ background-color: #e8f6f3; border-left: 4px solid #1abc9c; padding: 10px; margin-top: 10px; }}
            .footer {{ text-align: center; font-size: 0.8em; color: #7f8c8d; margin-top: 30px; }}
        </style>
    </head>
    <body>
        <div class="container">
            <div class="header">
                <h1>Daily AI Investment Insider</h1>
                <p>{date_str}</p>
            </div>
    """
    
    if not items:
        html_content += "<p>No new updates found in the last 24 hours.</p>"
    else:
        for item in items:
            # Fallback if analysis failed but we still want to show the link
            title = item.get('title_cn', item.get('title', 'Unknown Title'))
            summary = item.get('summary_cn', 'No summary available.')
            insight = item.get('key_insight', '')
            category = item.get('category', 'General')
            source = item.get('source_name', 'Unknown Source')
            url = item.get('url', '#')
            
            html_content += f"""
            <div class="item">
                <h2><a href="{url}" style="text-decoration: none; color: #2980b9;">{title}</a></h2>
                <div class="meta">
                    <span class="category">{category}</span> | Source: {source}
                </div>
                <p>{summary}</p>
                {f'<div class="insight"><strong>💡 Investment Insight:</strong> {insight}</div>' if insight else ''}
            </div>
            """
            
    html_content += """
            <div class="footer">
                <p>Generated by AI Investment Aggregator</p>
            </div>
        </div>
    </body>
    </html>
    """
    
    return html_content

def send_email(subject, html_body):
    """
    Send the email using SMTP.
    """
    if not config.EMAIL_PASSWORD or not config.EMAIL_SENDER or not config.EMAIL_RECIPIENT:
        logger.warning("Email configuration missing. Skipping email send.")
        # For debugging/dry-run, write to file
        with open("latest_report.html", "w", encoding="utf-8") as f:
            f.write(html_body)
        logger.info("Saved email to latest_report.html")
        return

    msg = MIMEMultipart()
    msg['From'] = config.EMAIL_SENDER
    msg['To'] = config.EMAIL_RECIPIENT
    msg['Subject'] = subject
    
    msg.attach(MIMEText(html_body, 'html'))
    
    try:
        # Assuming Gmail for now, but this should be configurable
        server = smtplib.SMTP('smtp.gmail.com', 587)
        server.starttls()
        server.login(config.EMAIL_SENDER, config.EMAIL_PASSWORD)
        text = msg.as_string()
        server.sendmail(config.EMAIL_SENDER, config.EMAIL_RECIPIENT, text)
        server.quit()
        logger.info("Email sent successfully.")
    except Exception as e:
        logger.error(f"Failed to send email: {e}")
